experiment_1: 
  alphas: 
    - 5.5
    - 3.7
  thetas: 
    - 2.5
  service_rates:
    - 0.9
    - 1.0
  runs: 50
  simulation_end: 5.0
  varying_iql: false
  max_iql: 0
  output_folder: 'data/simulation'

experiment_2: 
  alphas: 
    - 5.5
    - 10.0
  thetas: 
    - 2.0
  service_rates:
    - 0.9
    - 1.0
  runs: 1
  simulation_end: 5.0
  varying_iql: false
  max_iql: 0
  output_folder: 'data/simulation'