experiment_1: # gamma experiments with worksload α ∈ {2.7,4.3},β ∈ {0.6,1.2},μ ∈ {0.7,0.9}.
  alphas:
    - 2.7
    - 4.3
  thetas:
    - 0.6
    - 1.2
  service_rates:
    - 0.7
    - 0.9
  runs: 1000
  simulation_end: 20
  varying_iql: true
  max_iql: 5
  output_folder: 'data/simulation'