experiment_1:
  hypoexp_m1_time_series_experiment: 1
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.2

experiment_2:
  hypoexp_m1_time_series_experiment: 2
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.1

experiment_3:
  hypoexp_m1_time_series_experiment: 3
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.2

experiment_4:
  hypoexp_m1_time_series_experiment: 4
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.1

experiment_5:
  hypoexp_m1_time_series_experiment: 5
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.2

experiment_6:
  hypoexp_m1_time_series_experiment: 6
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.5 # 0.578 # TODO: run again for 0.5 

experiment_7:
  hypoexp_m1_time_series_experiment: 7
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.5

experiment_8:
  hypoexp_m1_time_series_experiment: 8
  time_discretization_folder: "discrete_time"
  sampling_interval: 0.547 # TODO: run again for 0.5 


