experiment_1:
  time_discretization_experiment: 1
  dbn_output_folder: "discrete_time"
  maximum_ql: 5
  expt_name: "hypoexpm1_contruct_dbn_exp_1"
  use_crosstab: True

experiment_2:
  time_discretization_experiment: 2
  dbn_output_folder: "discrete_time"
  maximum_ql: 5
  expt_name: "hypoexpm1_contruct_dbn_exp_2"
  use_crosstab: True

experiment_3:
  time_discretization_experiment: 3
  dbn_output_folder: "discrete_time"
  maximum_ql: 5
  expt_name: "hypoexpm1_contruct_dbn_exp_3"
  use_crosstab: True

experiment_4:
  time_discretization_experiment: 4
  dbn_output_folder: "discrete_time"
  maximum_ql: 5
  expt_name: "hypoexpm1_contruct_dbn_exp_4"
  use_crosstab: True

experiment_5:
  time_discretization_experiment: 5
  dbn_output_folder: "discrete_time"
  maximum_ql: 5
  expt_name: "hypoexpm1_contruct_dbn_exp_5"
  use_crosstab: True

experiment_6:
  time_discretization_experiment: 6
  dbn_output_folder: "discrete_time"
  maximum_ql: 5
  expt_name: "hypoexpm1_contruct_dbn_exp_6"
  use_crosstab: True

experiment_7:
  time_discretization_experiment: 7
  dbn_output_folder: "discrete_time"
  maximum_ql: 5
  expt_name: "hypoexpm1_contruct_dbn_exp_7"
  use_crosstab: True