"""
Visualize the event data generated by the simulator for M/M/1 queuing networks. 
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


def read_data(file_path):
    """
    Read the event data from the file specified by file_path. 
    """
    data = pd.read_csv(file_path)
    data.columns = [
        "Run", "Lambda", "Mu_parent", "Mu_child1", "Mu_child2", "Pchild1", "Pchild2", "End", "Time", "Event",
        "ParentQL", "Child1QL", "Child2QL"
    ]
    return data


def plot_queue_length(data, run, lambda_val, mu_parent, mu_child1, mu_child2):
    """
    Plot the queue length as a function of time for the specified run and parameter values. 
    """
    run_data = data[(data["Run"] == run) & (data["Lambda"] == lambda_val) &
                    (data["Mu_parent"] == mu_parent) &
                    (data["Mu_child1"] == mu_child1) &
                    (data["Mu_child2"] == mu_child2)]
    # Plot the queue length as step function
    plt.step(run_data["Time"], run_data["ParentQL"], label="Parent")
    plt.step(run_data["Time"], run_data["Child1QL"], label="Child 1")
    plt.step(run_data["Time"], run_data["Child2QL"], label="Child 2")
    plt.xlabel("Time")
    plt.ylabel("Queue Length")
    plt.title(f"Queue Length vs. Time for Run {run}")
    plt.legend()
    plt.savefig(f"figures/debugging/queue-length-run-{run}.png")


def time_sequence_plot(data, run, lambda_val, mu_parent, mu_child1, mu_child2):
    """Creates the following plot. 

    The time is plotted on the x-axis. 
    On the y-axis, we have three lines, one for the parent, one for child 1 and one for child 2. 

    For each line, we plot "Arrival Parent" using a green dot, "Departure Parent" using a red square. 
    """
    run_data = data[(data["Run"] == run) & (data["Lambda"] == lambda_val) &
                    (data["Mu_parent"] == mu_parent) &
                    (data["Mu_child1"] == mu_child1) &
                    (data["Mu_child2"] == mu_child2)]
    # Create a plot with 3 subplots sharing the same x-axis which plots the time.
    fig, axs = plt.subplots(3, sharex=True, sharey=True)
    fig.suptitle(f"Time Sequence for Run {run}")
    # Create a list of all "Parent Arrival" times
    parent_arrival_times = run_data[run_data["Event"] ==
                                    "Arrival Parent"]["Time"]
    # Create a list of all "Parent Departure" times
    parent_departure_times = run_data[run_data["Event"] ==
                                      "Departure Parent"]["Time"]
    axs[0].plot(parent_arrival_times,
                np.zeros_like(parent_arrival_times),
                'g.',
                label="Arrival",
                markersize=15)
    axs[0].plot(parent_departure_times,
                np.zeros_like(parent_departure_times),
                'r^',
                label="Departure",
                markersize=10)
    axs[0].set_title("Parent")
    # Create a list of all "Child 1 Arrival" times
    child1_arrival_times = run_data[run_data["Event"] ==
                                    "Arrival Child1"]["Time"]
    # Create a list of all "Child 1 Departure" times
    child1_departure_times = run_data[run_data["Event"] ==
                                      "Departure Child1"]["Time"]
    axs[1].plot(child1_arrival_times,
                np.zeros_like(child1_arrival_times),
                'g.',
                label="Arrival Child 1",
                markersize=15)
    axs[1].plot(child1_departure_times,
                np.zeros_like(child1_departure_times),
                'r^',
                label="Departure Child 1",
                markersize=10)
    axs[1].set_title("Child 1")
    # Create a list of all "Child 2 Arrival" times
    child2_arrival_times = run_data[run_data["Event"] ==
                                    "Arrival Child2"]["Time"]
    # Create a list of all "Child 2 Departure" times
    child2_departure_times = run_data[run_data["Event"] ==
                                      "Departure Child2"]["Time"]
    axs[2].plot(child2_arrival_times,
                np.zeros_like(child2_arrival_times),
                'g.',
                label="Arrival Child 2",
                markersize=15)
    axs[2].plot(child2_departure_times,
                np.zeros_like(child2_departure_times),
                'r^',
                label="Departure Child 2",
                markersize=10)
    axs[2].set_title("Child 2")
    plt.xlabel("Time")
    # Have a common legend for all subplots
    axs[0].legend()
    # Save the plot
    plt.savefig(f"figures/debugging/time-sequence-run-{run}.png")


time_sequence_plot(
    read_data(
        "data/time-series-lambda-[0.25, 0.5]-mu_p-1.0-mu_c1-0.2-mu_c2-0.3-r_pc1-0.5-runs-1-end-20.0.csv"
    ), 2, 0.5, 1.0, 0.2, 0.3)
